### ISSUE TITLE
Handle Rich Text element possibly containing empty string

### ISSUE THREAD

**Issue by zbynekh** [Kentico/kontent-delivery-sdk-php#87]
### Motivation

While introducing new feature Default value of element Kontent Delivery will no longer ensure empty paragraph is returned when Rich Text element is empty. PHP SDK should be able to handle also empty string while parsing the Rich Text value.

### Proposed solution

Now, SDK will most probably fail in this package used: https://github.com/Kub-AT/php-simple-html-dom-parser/blob/master/src/KubAT/PhpSimple/lib/simple_html_dom.php#L117. This should be fixed as the empty string becomes also a valid input.

**Comment by Simply007** [comment]
Internal link: https://kentico.atlassian.net/browse/KCL-3380
